[project]
name = "anonymous-messages"
version = "0.1.0"
description = "Small telegram bot that allow you to receive anonymous messages."
readme = "README.md"
authors = [
    { name = "Erra Edmond", email = "125184225+ErraEdmond@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiogram==3.31.0",
    "aiosqlite>=0.22.1",
    "sqlalchemy==2.0.35",
]

[tool.pyright]
    venvPath = "."
    venv = ".venv"

[tool.uv]
    package = false
