[project]
name = "anonymous-messages"
version = "0.1.0"
description = "Small telegram bot that allow you to receive anonymous messages."
readme = "README.md"
authors = [
    { name = "Erra Edmond", email = "125184225+ErraEdmond@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiofiles==23.2.1",
    "aiogram>=3.13.1",
    "aiohttp==3.9.5",
    "aiosignal==1.3.1",
    "aiosqlite==0.20.0",
    "annotated-types==0.7.0",
    "astroid==4.0.2",
    "attrs==24.2.0",
    "certifi==2024.7.4",
    "dill==0.4.0",
    "frozenlist==1.4.1",
    "greenlet==3.1.0",
    "idna==3.7",
    "magic-filter==1.0.12",
    "mccabe==0.7.0",
    "multidict==6.0.5",
    "platformdirs==4.5.0",
    "pydantic==2.9.2",
    "setuptools==65.5.0",
    "sqlalchemy==2.0.35",
    "tomlkit==0.13.3",
    "typing-extensions==4.12.2",
    "yarl==1.9.4",
]

[tool.uv]
    package = false
